import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#0a1b2c' },
  bg: { flex: 1 },
  navRoot: { flex: 1 },
  navContent: { flex: 1 },
  wrap: { padding: 14, paddingBottom: 28, gap: 10 },
  tableScreen: { flex: 1, padding: 10, gap: 8 },
  tableCore: { flex: 1, gap: 8, flexDirection: 'row', minHeight: 0 },

  brandBlock: { gap: 3, marginBottom: 4, flexShrink: 1, paddingRight: 8 },
  brandBlockMini: { gap: 2 },
  brandText: { color: '#6ff0b9', fontSize: 12, letterSpacing: 2, fontFamily: 'monospace' },
  h1: { fontSize: 26, fontWeight: '900', color: '#ecfff7', fontFamily: 'serif' },
  sub: { fontSize: 12, color: '#a8d6c7' },

  topRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
  topActions: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', justifyContent: 'flex-end', flexShrink: 1, maxWidth: '58%' },
  iconBtn: {
    minWidth: 50,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2c5f6a',
    backgroundColor: '#112733',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  iconBtnText: { color: '#e1f5ff', fontSize: 12, fontWeight: '700' },
  iconEmoji: { fontSize: 18 },

  lobbyScreen: { flex: 1, position: 'relative', overflow: 'hidden', padding: 10, gap: 8 },
  lobbyScreenCompact: { padding: 8, gap: 6 },
  lobbyAuraA: {
    position: 'absolute',
    width: 340,
    height: 340,
    borderRadius: 999,
    backgroundColor: 'rgba(44, 187, 160, 0.14)',
    top: -140,
    left: -110,
  },
  lobbyAuraB: {
    position: 'absolute',
    width: 420,
    height: 420,
    borderRadius: 999,
    backgroundColor: 'rgba(38, 131, 196, 0.12)',
    bottom: -210,
    right: -140,
  },
  lobbyMarquee: {
    borderWidth: 1,
    borderColor: '#317b68',
    borderRadius: 10,
    backgroundColor: 'rgba(11, 48, 39, 0.80)',
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  lobbyMarqueeText: { color: '#9af8d3', fontSize: 11, fontWeight: '700', fontFamily: 'monospace' },
  lobbyHeader: {
    borderWidth: 1,
    borderColor: '#397990',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 9,
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  lobbyHeaderCompact: { paddingHorizontal: 10, paddingVertical: 8, gap: 8 },
  h1Compact: { fontSize: 22 },
  subCompact: { fontSize: 11 },
  lobbyHeaderStats: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-end', gap: 6, flex: 1, maxWidth: '55%' },
  lobbyHeaderStatsWithGear: { paddingRight: 44 },
  lobbyHeaderGearBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 36,
    height: 36,
    borderWidth: 1,
    borderColor: '#4f8ca2',
    borderRadius: 18,
    backgroundColor: 'rgba(11, 37, 52, 0.88)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lobbyHeaderGearBtnCompact: { top: 6, right: 6, width: 32, height: 32, borderRadius: 16 },
  lobbyHeaderGearBtnOn: { borderColor: '#85ffe4', backgroundColor: 'rgba(18, 78, 65, 0.88)' },
  lobbyHeaderGearIcon: { color: '#dff5ff', fontSize: 18, fontWeight: '900', lineHeight: 20 },
  lobbyHeaderStat: {
    minWidth: 86,
    borderWidth: 1,
    borderColor: '#2a5f75',
    borderRadius: 9,
    backgroundColor: 'rgba(8, 29, 42, 0.82)',
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 1,
  },
  lobbyHeaderStatLabel: { color: '#9cc3d3', fontSize: 9, fontFamily: 'monospace' },
  lobbyHeaderStatValue: { color: '#f0fff9', fontSize: 13, fontWeight: '900' },
  lobbyBody: { flex: 1, minHeight: 0, flexDirection: 'row', gap: 8 },
  lobbyBodyCompact: { gap: 6 },
  lobbySettingsOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 25,
    justifyContent: 'center',
    alignItems: 'flex-end',
    padding: 10,
  },
  lobbySettingsBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(4, 9, 15, 0.58)',
  },
  lobbySettingsPanel: {
    width: '58%',
    maxWidth: 640,
    minWidth: 320,
    maxHeight: '94%',
    borderWidth: 1,
    borderColor: '#3f6f84',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  lobbySettingsHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
  lobbySettingsTitle: { color: '#f2fffb', fontSize: 20, fontWeight: '900', fontFamily: 'serif' },
  lobbySettingsScroll: { minHeight: 0 },
  lobbySettingsScrollContent: { gap: 8, paddingBottom: 6 },
  lobbySettingCard: {
    borderWidth: 1,
    borderColor: '#39687a',
    borderRadius: 10,
    backgroundColor: 'rgba(10, 36, 49, 0.8)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
  },
  lobbySettingTitle: { color: '#ecfff8', fontSize: 15, fontWeight: '900', fontFamily: 'serif' },
  lobbySettingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  lobbySettingRowCopy: { flex: 1, gap: 2 },
  lobbySettingRowTitle: { color: '#def6ff', fontSize: 12, fontWeight: '800' },
  lobbySettingRowSub: { color: '#9ebfce', fontSize: 10 },
  lobbySettingSwitch: {
    minWidth: 48,
    borderWidth: 1,
    borderColor: '#456a7a',
    borderRadius: 999,
    backgroundColor: '#1a3a48',
    paddingHorizontal: 12,
    paddingVertical: 5,
    alignItems: 'center',
  },
  lobbySettingSwitchOn: { borderColor: '#8dffe5', backgroundColor: '#1d5a4d' },
  lobbySettingSwitchText: { color: '#e1f6ff', fontSize: 10, fontWeight: '800' },
  voiceDrawerCard: {
    borderWidth: 1,
    borderColor: '#3b6778',
    borderRadius: 10,
    backgroundColor: 'rgba(15, 47, 60, 0.82)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 8,
  },
  voiceDrawerToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  voiceDrawerToggleCopy: { flex: 1, gap: 2 },
  voiceDrawerAdviceBox: {
    borderWidth: 1,
    borderColor: '#4a7181',
    borderRadius: 8,
    backgroundColor: '#14303c',
    paddingHorizontal: 8,
    paddingVertical: 7,
    gap: 3,
  },
  voiceDrawerAdviceLabel: { color: '#d9f0ff', fontSize: 11, fontWeight: '800' },
  lobbyRoomsPanel: {
    flex: 1.5,
    borderWidth: 1,
    borderColor: '#2d6178',
    borderRadius: 14,
    padding: 8,
    gap: 6,
    minHeight: 0,
  },
  lobbyRoomsHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  lobbyRoomsTitle: { color: '#e8fff8', fontSize: 15, fontWeight: '900', fontFamily: 'serif' },
  lobbyRoomGrid: { flex: 1, minHeight: 0, flexDirection: 'row', flexWrap: 'wrap', rowGap: 6, columnGap: 6, alignContent: 'space-between' },
  lobbyRoomGridCompact: { rowGap: 4, columnGap: 4 },
  lobbyRoomTouch: { width: '32.4%', height: '46.8%', minHeight: 0, borderRadius: 12 },
  lobbyRoomTouchCompact: { width: '32.4%', height: '45.2%' },
  lobbyRoomCard: { borderWidth: 1, borderColor: '#2f5f72', borderRadius: 12, paddingHorizontal: 7, paddingVertical: 6, gap: 4, flex: 1 },
  lobbyRoomCardCompact: { paddingHorizontal: 6, paddingVertical: 5, gap: 3 },
  lobbyRoomCardOn: {
    borderColor: '#79ffe0',
    shadowColor: '#5effd8',
    shadowOpacity: 0.32,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 0 },
    elevation: 5,
  },
  lobbyRoomLocked: { opacity: 0.65 },
  lobbyRoomCardHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 6 },
  lobbyRoomTitle: { color: '#f3fffc', fontWeight: '900', fontSize: 15, fontFamily: 'serif', flexShrink: 1 },
  lobbyRoomTitleCompact: { fontSize: 13 },
  lobbyRoomSub: { color: '#a8ccdb', fontSize: 9 },
  lobbyRoomSubCompact: { fontSize: 8 },
  lobbyDoorChip: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 8,
    paddingVertical: 2,
    color: '#cef6ea',
    fontFamily: 'monospace',
    fontSize: 9,
    fontWeight: '800',
  },
  lobbyDoorChipOpen: { borderColor: '#2f866d', backgroundColor: 'rgba(19, 82, 65, 0.72)' },
  lobbyDoorChipLive: { borderColor: '#72ffd8', backgroundColor: 'rgba(21, 112, 90, 0.86)', color: '#e8fff7' },
  lobbyDoorChipLocked: { borderColor: '#4a6279', backgroundColor: 'rgba(36, 52, 67, 0.84)', color: '#afc5d9' },
  lobbyRoomMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  lobbyRoomMeta: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#2f5f70',
    backgroundColor: 'rgba(8, 26, 39, 0.82)',
    color: '#d7ecf7',
    fontFamily: 'monospace',
    fontSize: 8,
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  lobbyRoomMetaCompact: { fontSize: 7, paddingHorizontal: 4 },
  lobbyRoomTail: { color: '#91ebc7', fontSize: 9, fontWeight: '700' },
  lobbyRoomTailCompact: { fontSize: 8 },
  lobbyRoomTailLocked: { color: '#b5c9d8' },
  lobbyControlPanel: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#2c6c6f',
    borderRadius: 14,
    padding: 10,
    gap: 8,
    minHeight: 0,
  },
  lobbyControlPanelCompact: { padding: 8, gap: 6 },
  lobbyControlContent: { flex: 1, minHeight: 0, gap: 8 },
  lobbyControlContentCompact: { gap: 5, justifyContent: 'space-between', paddingBottom: 8 },
  lobbyControlTop: { gap: 6 },
  lobbyControlTopCompact: { gap: 4, flexShrink: 1 },
  lobbyControlBottom: { gap: 6 },
  lobbyControlBottomCompact: { gap: 4, marginTop: 2, marginBottom: 6 },
  lobbyControlTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 8 },
  lobbyControlTitleRowCompact: { gap: 6 },
  lobbyControlTitle: { color: '#f2fffa', fontSize: 20, fontWeight: '900', fontFamily: 'serif' },
  lobbyControlTitleCompact: { fontSize: 16 },
  lobbyControlSub: { color: '#b7d8cd', fontSize: 11, maxWidth: 250 },
  lobbyControlSubCompact: { fontSize: 10, maxWidth: 200 },
  lobbyModeRow: { flexDirection: 'row', gap: 8 },
  lobbyModeRowCompact: { gap: 6 },
  lobbyModeBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#3e6674',
    borderRadius: 8,
    backgroundColor: 'rgba(10, 33, 45, 0.82)',
    paddingVertical: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lobbyModeBtnCompact: { paddingVertical: 5 },
  lobbyModeBtnOn: {
    borderColor: '#86ffe3',
    backgroundColor: 'rgba(18, 72, 59, 0.82)',
  },
  lobbyModeBtnText: { color: '#c5dce9', fontSize: 11, fontWeight: '800' },
  lobbyModeBtnTextCompact: { fontSize: 10 },
  lobbyModeBtnTextOn: { color: '#ebfff7' },
  lobbyModeHint: { color: '#b8d8ce', fontSize: 10, lineHeight: 14 },
  lobbyModeHintCompact: { fontSize: 9, lineHeight: 12 },
  lobbyFocusList: {
    borderWidth: 1,
    borderColor: '#35696b',
    borderRadius: 10,
    backgroundColor: 'rgba(9, 38, 34, 0.72)',
    paddingHorizontal: 9,
    paddingVertical: 7,
    gap: 4,
  },
  lobbyFocusListCompact: { paddingHorizontal: 7, paddingVertical: 4, gap: 2 },
  lobbyFocusLine: { color: '#d9f8e9', fontSize: 11 },
  lobbyFocusLineCompact: { fontSize: 10 },
  lobbyControlMetaGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  lobbyControlMetaGridCompact: { gap: 4 },
  lobbyControlMetaCard: {
    width: '48.5%',
    borderWidth: 1,
    borderColor: '#345f70',
    borderRadius: 8,
    backgroundColor: 'rgba(9, 30, 43, 0.78)',
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 2,
  },
  lobbyControlMetaCardCompact: { paddingHorizontal: 6, paddingVertical: 4, gap: 1 },
  lobbyControlMetaLabel: { color: '#9dbac8', fontSize: 9, fontFamily: 'monospace' },
  lobbyControlMetaLabelCompact: { fontSize: 8 },
  lobbyControlMetaValue: { color: '#f2fffb', fontSize: 12, fontWeight: '800' },
  lobbyControlMetaValueCompact: { fontSize: 10 },
  primaryGradCompact: { paddingVertical: 6 },
  primaryTextCompact: { fontSize: 10 },
  lobbyControlNote: { color: '#b8d8ce', fontSize: 10, lineHeight: 14 },

  tableShell: { borderRadius: 24, overflow: 'hidden', flex: 1, minHeight: 0, minWidth: 0 },
  tableRail: { borderRadius: 24, padding: 8, borderWidth: 1, borderColor: '#9a7441', flex: 1 },
  tableFelt: { position: 'relative', borderRadius: 20, overflow: 'hidden', flex: 1, minHeight: 0 },
  feltGlowA: { position: 'absolute', width: 250, height: 250, borderRadius: 999, backgroundColor: 'rgba(64, 185, 138, 0.10)', left: '18%', top: '16%' },
  feltGlowB: { position: 'absolute', width: 180, height: 180, borderRadius: 999, backgroundColor: 'rgba(122, 245, 194, 0.08)', right: '10%', bottom: '10%' },

  centerBoardWrap: {
    position: 'absolute',
    left: '23%',
    right: '23%',
    top: '30%',
    borderRadius: 16,
    paddingVertical: 6,
    alignItems: 'center',
    backgroundColor: 'rgba(8, 32, 29, 0.82)',
    borderWidth: 1,
    borderColor: '#2a6153',
    gap: 4,
    zIndex: 6,
  },
  centerLabel: { color: '#f6fffb', fontSize: 14, fontWeight: '900', fontFamily: 'monospace' },
  centerSub: { color: '#99d5c3', fontSize: 10, fontFamily: 'monospace' },
  chipPulse: { position: 'absolute', top: 10, right: 12 },
  chipPulseText: { color: '#f7d27d', fontSize: 16, fontWeight: '900' },
  boardRow: { flexDirection: 'row', gap: 4, alignItems: 'center' },

  seatCards: {
    position: 'absolute',
    flexDirection: 'row',
    gap: 4,
    zIndex: 30,
    elevation: 12,
  },
  seatCardsOffset: {
    marginLeft: 16,
    marginTop: 14,
  },
  seatBadge: {
    position: 'absolute',
    width: 86,
    marginLeft: -43,
    marginTop: -22,
    paddingVertical: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#29554a',
    backgroundColor: 'rgba(8, 22, 22, 0.86)',
    alignItems: 'center',
    gap: 1,
    zIndex: 14,
  },
  seatBadgeOn: { borderColor: '#83ffe4' },
  seatBadgeBattle: { borderColor: '#f5d38a' },
  seatBadgeEmpty: { opacity: 0.44 },
  seatBadgeFolded: { opacity: 0.5 },
  avatarDot: { width: 7, height: 7, borderRadius: 999, backgroundColor: '#57ffc8' },
  seatPos: { color: '#ffe6b3', fontSize: 9, fontWeight: '800', fontFamily: 'monospace' },
  seatName: { color: '#f1fffb', fontSize: 10, fontWeight: '800' },
  seatStack: { color: '#8fd9bd', fontSize: 9, fontFamily: 'monospace' },
  seatActionText: { color: '#9ecad8', fontSize: 9, fontFamily: 'monospace' },

  tableCard: {
    width: 38,
    height: 54,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#a0adbc',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  tableCardCompact: {
    width: 30,
    height: 44,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#a0adbc',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  cardBack: { borderColor: '#364f7c' },
  cardBackStripe: { position: 'absolute', top: 0, bottom: 0, width: 9, backgroundColor: 'rgba(118, 158, 238, 0.25)' },
  cardBackText: { color: '#d5e6ff', fontWeight: '900', fontSize: 12 },
  cardFaceText: { color: '#0f1825', fontWeight: '900', fontSize: 15, fontFamily: 'serif' },
  cardFaceRed: { color: '#a91c2f' },

  row3: { flexDirection: 'row', gap: 6, alignItems: 'center' },
  actionDock: {
    width: '31%',
    minWidth: 240,
    maxWidth: 320,
    flexGrow: 0,
    flexShrink: 0,
    borderWidth: 1,
    borderColor: '#245564',
    borderRadius: 12,
    backgroundColor: 'rgba(9, 29, 40, 0.88)',
    padding: 8,
    gap: 8,
    justifyContent: 'space-between',
  },
  actionDockTop: {
    flex: 1,
    minHeight: 0,
    gap: 8,
    overflow: 'hidden',
  },
  actionDockBottom: {
    gap: 8,
  },
  replacementPrompt: {
    borderWidth: 1,
    borderColor: '#3c6776',
    borderRadius: 9,
    backgroundColor: 'rgba(10, 39, 52, 0.76)',
    paddingHorizontal: 8,
    paddingVertical: 7,
    gap: 6,
  },
  actionSummaryCard: {
    flex: 1,
    minHeight: 0,
    borderWidth: 1,
    borderColor: '#316374',
    borderRadius: 10,
    backgroundColor: 'rgba(10, 38, 52, 0.72)',
    paddingHorizontal: 8,
    paddingVertical: 7,
    gap: 4,
    overflow: 'hidden',
  },
  actionSummaryScroll: {
    flex: 1,
    minHeight: 0,
  },
  actionSummaryScrollContent: {
    gap: 4,
    paddingBottom: 2,
  },
  actionSummaryTitle: {
    color: '#d7f4ff',
    fontSize: 11,
    fontWeight: '800',
  },
  actionSummaryLine: {
    color: '#b9dcec',
    fontSize: 10,
    fontFamily: 'monospace',
  },
  actionSummaryEmpty: {
    color: '#83b3c6',
    fontSize: 10,
    fontFamily: 'monospace',
  },
  panel: {
    borderWidth: 1,
    borderColor: '#245564',
    borderRadius: 12,
    backgroundColor: 'rgba(9, 29, 40, 0.88)',
    padding: 10,
    gap: 6,
  },
  panelBlue: {
    borderWidth: 1,
    borderColor: '#447086',
    borderRadius: 12,
    backgroundColor: 'rgba(14, 39, 52, 0.95)',
    padding: 10,
    gap: 6,
  },
  analysisVoiceCard: {
    borderWidth: 1,
    borderColor: '#4a7488',
    borderRadius: 10,
    backgroundColor: 'rgba(18, 45, 58, 0.92)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  opsScrollContent: { gap: 12, paddingBottom: 16, paddingTop: 10 },
  opsHeroCard: {
    borderWidth: 1,
    borderColor: '#4f7f95',
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  opsHeroTitle: { color: '#f0fbff', fontSize: 22, fontWeight: '900' },
  opsHeroSub: { color: '#bde4f2', fontSize: 12, fontWeight: '700' },
  opsHeroGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  opsHeroItem: {
    minWidth: 130,
    flexGrow: 1,
    borderWidth: 1,
    borderColor: '#5b8596',
    borderRadius: 10,
    backgroundColor: 'rgba(8, 30, 43, 0.6)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  opsHeroLabel: { color: '#a8d0de', fontSize: 10, fontWeight: '700' },
  opsHeroValue: { color: '#ebfcff', fontSize: 18, fontWeight: '900', fontFamily: 'monospace' },
  opsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, alignItems: 'flex-start' },
  opsGridCard: { flexBasis: 520, flexGrow: 1, minWidth: 320 },
  coachStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  coachStatTile: {
    flexBasis: 200,
    flexGrow: 1,
    minWidth: 178,
    borderWidth: 1,
    borderColor: '#4e7384',
    borderRadius: 8,
    backgroundColor: '#173847',
    paddingHorizontal: 8,
    paddingVertical: 7,
    gap: 5,
  },
  coachStatHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  coachStatRate: {
    color: '#e7f7ff',
    fontSize: 12,
    fontWeight: '900',
    fontFamily: 'monospace',
  },
  coachStatMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 6,
  },
  coachStatCount: {
    color: '#9fc3d3',
    fontSize: 10,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  coachStatRange: {
    color: '#9fc3d3',
    fontSize: 10,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  coachStatBenchmark: {
    fontSize: 10,
    fontWeight: '800',
    fontFamily: 'monospace',
  },
  coachStatBenchmarkPending: { color: '#a2b2bc' },
  coachStatBenchmarkInRange: { color: '#8fe0bf' },
  coachStatBenchmarkHigh: { color: '#f3bb86' },
  coachStatBenchmarkLow: { color: '#88b5ff' },
  coachStatTier: {
    fontSize: 10,
    fontWeight: '800',
  },
  coachStatTierLow: { color: '#b7c2c9' },
  coachStatTierMid: { color: '#e3d08e' },
  coachStatTierHigh: { color: '#8fe0bf' },
  missionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  missionResetBtn: {
    borderWidth: 1,
    borderColor: '#4f7f92',
    borderRadius: 8,
    backgroundColor: '#194153',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  missionResetText: { color: '#e1f5ff', fontSize: 10, fontWeight: '700' },
  missionCard: {
    borderWidth: 1,
    borderColor: '#4d6f7f',
    borderRadius: 8,
    backgroundColor: '#15303d',
    padding: 8,
    gap: 3,
  },
  missionCardDone: {
    borderColor: '#4fae8a',
    backgroundColor: '#183c34',
  },
  missionTitle: { color: '#eef8ff', fontWeight: '900', fontSize: 12 },
  bankruptcyOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(3, 8, 14, 0.76)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
    zIndex: 40,
  },
  bankruptcyScroll: { width: '100%' },
  bankruptcyScrollContent: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 12 },
  bankruptcyCard: {
    width: '100%',
    maxWidth: 680,
    maxHeight: '94%',
    borderWidth: 1,
    borderColor: '#925e40',
    borderRadius: 14,
    backgroundColor: 'rgba(31, 17, 12, 0.97)',
    padding: 14,
    gap: 8,
  },
  bankruptcyTitle: { color: '#ffe3c7', fontSize: 19, fontWeight: '900' },
  bankruptcyText: { color: '#fff2e1', fontSize: 12, lineHeight: 18 },
  bankruptcyHint: { color: '#f2c899', fontSize: 11, fontWeight: '700' },
  bankruptcyCoachHint: { color: '#f3d7b5', fontSize: 11, lineHeight: 16 },
  bankruptcyActionRow: { flexDirection: 'row', gap: 8, alignItems: 'stretch', flexWrap: 'wrap' },
  bankruptcyActionBtn: {
    flex: 1,
    minWidth: 220,
    borderWidth: 1,
    borderColor: '#7f5a45',
    borderRadius: 9,
    backgroundColor: 'rgba(49, 26, 17, 0.9)',
    paddingHorizontal: 9,
    paddingVertical: 8,
    gap: 2,
  },
  bankruptcyActionTitle: { color: '#fff0df', fontSize: 11, fontWeight: '900' },
  bankruptcyActionSub: { color: '#f1caa2', fontSize: 10, fontWeight: '700' },
  drawerRoot: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  drawerBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(4, 8, 14, 0.6)',
  },
  drawerBackdropTouch: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  drawerPanel: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    width: '76%',
    maxWidth: 1180,
    minWidth: 360,
    borderWidth: 1,
    borderColor: '#3f6675',
    borderTopLeftRadius: 14,
    borderBottomLeftRadius: 14,
    backgroundColor: 'rgba(8, 22, 32, 0.98)',
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 6,
    gap: 6,
  },
  opsDrawerPanel: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    width: '100%',
    borderWidth: 1,
    borderColor: '#3a6272',
    backgroundColor: 'rgba(8, 22, 32, 0.99)',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
    gap: 8,
  },
  missionDrawerPanel: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    width: '33%',
    maxWidth: 460,
    minWidth: 300,
    borderWidth: 1,
    borderColor: '#4d6f7f',
    borderTopLeftRadius: 14,
    borderBottomLeftRadius: 14,
    backgroundColor: 'rgba(8, 22, 32, 0.98)',
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 6,
    gap: 6,
  },
  voiceDrawerPanel: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    width: '34%',
    maxWidth: 520,
    minWidth: 300,
    borderWidth: 1,
    borderColor: '#3f6675',
    borderTopLeftRadius: 14,
    borderBottomLeftRadius: 14,
    backgroundColor: 'rgba(8, 22, 32, 0.98)',
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 6,
    gap: 6,
  },
  drawerHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  drawerScroll: { flex: 1 },
  drawerScrollContent: { gap: 8, paddingBottom: 10, paddingTop: 8 },

  raiseRow: { gap: 6 },
  raiseValue: { color: '#d9f4ff', fontWeight: '800', fontFamily: 'monospace', fontSize: 12 },
  raiseSliderTrack: {
    height: 30,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#4f7191',
    backgroundColor: '#112f42',
    overflow: 'hidden',
    justifyContent: 'center',
    position: 'relative',
  },
  raiseSliderTrackDisabled: { opacity: 0.4 },
  raiseSliderFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
  },
  raiseSliderThumb: {
    position: 'absolute',
    top: 4,
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#e9f7ff',
    backgroundColor: '#4fb2d6',
    transform: [{ translateX: -11 }],
  },
  raiseSliderThumbAllIn: {
    borderColor: '#ffe7b3',
    backgroundColor: '#d9ab4a',
  },
  raiseMetaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  raiseMetaText: { color: '#90b9cb', fontSize: 11, fontWeight: '700' },
  raiseMetaTextHot: { color: '#ffdca1' },
  nextEventBtn: {
    borderWidth: 1,
    borderColor: '#46a4cf',
    borderRadius: 9,
    backgroundColor: '#184a62',
    paddingVertical: 7,
    alignItems: 'center',
  },
  nextEventBtnText: { color: '#e7f7ff', fontWeight: '800', fontSize: 11 },

  actionDanger: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#974f57',
    backgroundColor: '#4e1f28',
    paddingVertical: 8,
    alignItems: 'center',
  },
  actionMain: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#47a3d3',
    backgroundColor: '#164966',
    paddingVertical: 8,
    alignItems: 'center',
  },
  actionGold: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#c89a42',
    backgroundColor: '#624716',
    paddingVertical: 8,
    alignItems: 'center',
  },
  actionText: { color: '#fff8e9', fontWeight: '900', fontSize: 12 },

  secondary: {
    flex: 1,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#336878',
    backgroundColor: '#123241',
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryText: { color: '#ddf4ff', fontWeight: '700', fontSize: 11, textAlign: 'center', paddingHorizontal: 4 },
  primary: { borderRadius: 10, overflow: 'hidden' },
  primaryGrad: { alignItems: 'center', justifyContent: 'center', paddingVertical: 10, borderRadius: 10 },
  primaryText: { color: '#ecfff8', fontSize: 12, fontWeight: '900', textAlign: 'center', paddingHorizontal: 6 },

  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    borderWidth: 1,
    borderColor: '#2f6a79',
    borderRadius: 999,
    backgroundColor: '#143846',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  chipOn: { borderColor: '#f8d78f', backgroundColor: '#4c3a1f' },
  chipText: { color: '#d7efff', fontSize: 11, fontWeight: '700' },

  adviceCompareRow: { flexDirection: 'row', gap: 8, alignItems: 'flex-start', flexWrap: 'wrap' },
  adviceCompareCol: { flex: 1, minWidth: 280 },
  adviceBox: { borderWidth: 1, borderColor: '#48748a', borderRadius: 8, backgroundColor: '#163a4a', padding: 8, gap: 3 },
  adviceTitle: { color: '#eef8ff', fontWeight: '900' },
  adviceMain: { color: '#d8efff', fontWeight: '800', fontSize: 12 },
  algoBox: { borderWidth: 1, borderColor: '#4d6f7f', borderRadius: 8, backgroundColor: '#15303d', padding: 8, gap: 2 },
  insightGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  insightCardWide: {
    flexBasis: 620,
    flexGrow: 1,
    minWidth: 320,
    borderWidth: 1,
    borderColor: '#4c7281',
    borderRadius: 10,
    backgroundColor: '#143340',
    padding: 8,
    gap: 6,
  },
  insightCard: {
    flexBasis: 320,
    flexGrow: 1,
    minWidth: 280,
    borderWidth: 1,
    borderColor: '#4b6d7d',
    borderRadius: 10,
    backgroundColor: '#14303c',
    padding: 8,
    gap: 6,
  },
  stackBarTrack: {
    height: 14,
    borderRadius: 999,
    overflow: 'hidden',
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#385362',
    backgroundColor: '#102532',
  },
  stackBarHero: { height: '100%', backgroundColor: '#50c8f0' },
  stackBarTie: { height: '100%', backgroundColor: '#e6c879' },
  stackBarVillain: { height: '100%', backgroundColor: '#7a879b' },
  stackLegendRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  stackLegendText: { color: '#b6d0db', fontSize: 10, fontWeight: '700' },
  meterRow: { gap: 4 },
  meterHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  meterTrack: {
    height: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#36505f',
    overflow: 'hidden',
    backgroundColor: '#0f2430',
  },
  meterFill: { height: '100%' },
  outsRow: {
    borderWidth: 1,
    borderColor: '#416173',
    borderRadius: 8,
    backgroundColor: '#173746',
    paddingHorizontal: 7,
    paddingVertical: 6,
    gap: 2,
  },
  outsRowTitle: { color: '#e2f5ff', fontSize: 11, fontWeight: '800' },
  rangeSampleWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 2 },
  rangeSamplePill: {
    borderWidth: 1,
    borderColor: '#4f7384',
    borderRadius: 999,
    backgroundColor: '#193847',
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    gap: 5,
  },
  rangeSampleText: { color: '#d9efff', fontSize: 11, fontWeight: '700' },
  rangeSampleTextMuted: { color: '#9dc3d4', fontSize: 10, fontWeight: '700' },

  noteCard: { borderWidth: 1, borderColor: '#3c6d55', borderRadius: 10, backgroundColor: 'rgba(18, 45, 32, 0.84)', padding: 10, gap: 3 },

  text: { color: '#eefcf6', fontWeight: '800' },
  textMuted: { color: '#c8e3ee', fontSize: 12 },
  textTiny: { color: '#c6dff1', fontSize: 11 },
  dim: { opacity: 0.45 },
});
