import type React from 'react';
import type { Animated, DimensionValue, GestureResponderEvent, LayoutChangeEvent } from 'react-native';
import type { Audio } from 'expo-av';

import { analyzeCurrentSpot } from '../../../engine/game';
import { buildSpotInsight } from '../../../engine/insights';
import type { RootTab, RootTabItem } from '../../../navigation/rootTabs';
import type { LocalProfile } from '../../../storage/localDb';
import type { ActionType, HandState, ProgressState } from '../../../types/poker';

import type * as Play from '../index';

export type AppLanguage = Play.AppLanguage;
export type OppLeakGuess = Play.OppLeakGuess;
export type Seat = Play.Seat;
export type SeatVisual = Play.SeatVisual;
export type TrainingMode = Play.TrainingMode;
export type ZoneTrainingState = Play.ZoneTrainingState;

export type TableViewProps = {
  activeProfile: LocalProfile | null;
  activeSeatAnimId: string | null;
  activeXpFactor: number;
  aiVoiceAssistEnabled: boolean;
  aiVoiceBroadcastText: string;
  analysis: ReturnType<typeof analyzeCurrentSpot>;
  analysisDrawerWidth: number;
  analysisOpen: boolean;
  appLanguage: AppLanguage;
  autoPlayEvents: boolean;
  battleSeat: Seat | null;
  battleSeatId: string | null;
  bankruptcyCountdown: number;
  bankruptcyPromptOpen: boolean;
  bankruptcyPromptText: string;
  callOrCheck: ActionType;
  canClaimSubsidyToday: boolean;
  canHeroActNow: boolean;
  canRaise: boolean;
  chipPulse: Animated.Value;
  completedMissionCount: number;
  drawerBackdropOpacity: Animated.Value;
  drawerTranslateX: Animated.Value;
  engineLabel: string;
  eventQueue: Play.TableEvent[];
  hand: HandState;
  handRecordCount: number;
  hasPendingEvent: boolean;
  headerHeroBb: number;
  headerHeroStack: number;
  heroEquityEdge: number;
  holes: number;
  isAllInRaise: boolean;
  leakGuess: OppLeakGuess | null;
  minRaise: number;
  missionBackdropOpacity: Animated.Value;
  missionOpen: boolean;
  missionTranslateX: Animated.Value;
  navCollapsedOffset: number;
  navDrawerOpen: boolean;
  navExpandedOffset: number;
  navSafeInsetLeft: number;
  note: string;
  opsBackdropOpacity: Animated.Value;
  opsOpen: boolean;
  opsTranslateX: Animated.Value;
  pendingReplacementSeatIds: string[];
  politeMode: boolean;
  progress: ProgressState;
  raiseAmount: number;
  raiseCap: number;
  raiseSliderPercent: DimensionValue;
  recentActionLines: string[];
  rootTab: RootTab;
  rootTabItems: RootTabItem[];
  seatPulse: Animated.Value;
  seatVisual: Record<string, SeatVisual>;
  seats: Seat[];
  selectedSeat: Seat;
  selectedSeatDisplayPos: string;
  selectedSeatId: string;
  sfxEnabled: boolean;
  sfxLoadError: boolean;
  sfxReady: boolean;
  soundsRef: React.MutableRefObject<Record<Play.SfxKey, Audio.Sound[]>>;
  spotInsight: ReturnType<typeof buildSpotInsight>;
  tableFeed: string[];
  topLeak: keyof ProgressState['leaks'];
  trainingMode: TrainingMode;
  visibleBoard: HandState['board'];
  voiceBackdropOpacity: Animated.Value;
  voiceDrawerOpen: boolean;
  voiceTranslateX: Animated.Value;
  zoneCareerXpFactor: number;
  zoneDisplayName: string;
  zoneHeroBb: number;
  zoneHeroStack: number;
  zoneLoanDebtBb: number;
  zoneProfitBb: number;
  zoneStatsCoachNote: string;
  zoneTrainingState: ZoneTrainingState;
  zoneVpipPfrGap: number;
  applyCareerBankruptcyRescue: (kind: 'subsidy' | 'loan') => void;
  continueInPracticeMode: () => void;
  doAction: (action: ActionType) => void;
  handleRaiseSliderGesture: (event: GestureResponderEvent) => void;
  handleRaiseSliderLayout: (event: LayoutChangeEvent) => void;
  handleRootTabChange: (tab: RootTab) => void;
  handleSeatTap: (seat: Seat) => void;
  handleTableScreenLayout: (event: LayoutChangeEvent) => void;
  resetZoneTrainingState: () => void;
  returnToLobbyAfterBankruptcy: () => void;
  runNextEvent: () => void;
  setAiVoiceAssistEnabled: React.Dispatch<React.SetStateAction<boolean>>;
  setAnalysisOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setAutoPlayEvents: React.Dispatch<React.SetStateAction<boolean>>;
  setLeakGuess: React.Dispatch<React.SetStateAction<OppLeakGuess | null>>;
  setMissionOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setNavDrawerOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setNote: React.Dispatch<React.SetStateAction<string>>;
  setOpsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setPhase: React.Dispatch<React.SetStateAction<Play.Phase>>;
  setPoliteMode: React.Dispatch<React.SetStateAction<boolean>>;
  setSfxEnabled: React.Dispatch<React.SetStateAction<boolean>>;
  setVoiceDrawerOpen: React.Dispatch<React.SetStateAction<boolean>>;
  stackText: (seat: Seat) => string;
  startHand: (targetSeatId?: string, options?: { zoneStateOverride?: ZoneTrainingState; modeOverride?: TrainingMode }) => void;
  verifyLeak: () => void;
};
